/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.codebutler.tunestreamer;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int expanding_child_background=0x7f070000;
    }
    public static final class dimen {
        public static final int row_height=0x7f050000;
    }
    public static final class drawable {
        public static final int albumart_mp_unknown_list=0x7f020000;
        public static final int ic_mp_playlist_list=0x7f020001;
        public static final int ic_tab_albums=0x7f020002;
        public static final int ic_tab_albums_selected=0x7f020003;
        public static final int ic_tab_albums_unselected=0x7f020004;
        public static final int ic_tab_artists=0x7f020005;
        public static final int ic_tab_artists_selected=0x7f020006;
        public static final int ic_tab_artists_unselected=0x7f020007;
        public static final int ic_tab_playback=0x7f020008;
        public static final int ic_tab_playback_selected=0x7f020009;
        public static final int ic_tab_playback_unselected=0x7f02000a;
        public static final int ic_tab_playlists=0x7f02000b;
        public static final int ic_tab_playlists_selected=0x7f02000c;
        public static final int ic_tab_playlists_unselected=0x7f02000d;
        public static final int ic_tab_songs=0x7f02000e;
        public static final int ic_tab_songs_selected=0x7f02000f;
        public static final int ic_tab_songs_unselected=0x7f020010;
        public static final int list_selector=0x7f020011;
    }
    public static final class id {
        public static final int duration=0x7f080003;
        public static final int icon=0x7f080002;
        public static final int line1=0x7f080004;
        public static final int line2=0x7f080005;
        public static final int play_indicator=0x7f080006;
        public static final int server_cancel=0x7f080001;
        public static final int server_save=0x7f080000;
    }
    public static final class layout {
        public static final int library=0x7f030000;
        public static final int library_list=0x7f030001;
        public static final int main=0x7f030002;
        public static final int server_prefs_buttons=0x7f030003;
        public static final int track_list_item=0x7f030004;
        public static final int track_list_item_child=0x7f030005;
        public static final int track_list_item_common=0x7f030006;
        public static final int track_list_item_group=0x7f030007;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
        /**  Do not translate. Duration format for duration >= 1 hour 
         */
        public static final int durationformatlong=0x7f060002;
        /**  Do not translate. Duration format for duration < 1 hour 
         */
        public static final int durationformatshort=0x7f060001;
        public static final int search_hint=0x7f060004;
        public static final int search_label=0x7f060003;
    }
    public static final class xml {
        public static final int searchable=0x7f040000;
        public static final int server_prefs=0x7f040001;
    }
}
